.TH "source/OpenSslErrors.cpp" 3 "Wed Jan 27 2021" "PubSub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/OpenSslErrors.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'headers/OpenSslErrors\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPubSub\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPubSub::printErrorsAndThrow\fP (const char *msg)"
.br
.ti -1c
.RI "void \fBPubSub::printErrorsAndExit\fP (const char *message)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PubSub from the source code\&.
