.TH "source/PublishRequest.cpp" 3 "Wed Jan 27 2021" "PubSub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/PublishRequest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'headers/Protocol/PublishDataRequest\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPubSub\fP"
.br
.ti -1c
.RI " \fBPubSub::Protocol\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PubSub from the source code\&.
