.TH "PubSub" 3 "Wed Jan 27 2021" "PubSub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PubSub
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBProtocol\fP"
.br
.ti -1c
.RI " \fBUtil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintErrorsAndThrow\fP (const char *msg)"
.br
.ti -1c
.RI "void \fBprintErrorsAndExit\fP (const char *message)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void PubSub::printErrorsAndExit (const char * message)"

.SS "void PubSub::printErrorsAndThrow (const char * msg)"

.SH "Author"
.PP 
Generated automatically by Doxygen for PubSub from the source code\&.
