.TH "source/Random.cpp" 3 "Wed Jan 27 2021" "PubSub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/Random.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'headers/Util/Random\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPubSub\fP"
.br
.ti -1c
.RI " \fBPubSub::Util\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBPubSub::Util::randomString\fP (const int len)"
.br
.ti -1c
.RI "int \fBPubSub::Util::randomInteger\fP (int min, int max)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PubSub from the source code\&.
